### ISSUE TITLE
How to set path that database is not under the original path?

### ISSUE THREAD

**Issue by ghost** [amitshekhariitbhu/Android-Debug-Database#1]
may be in storage?

**Comment by amitshekhariitbhu** [comment]
@zuri-yi ... seems nice features, I will add it in new release.

Thanks
Amit Shekhar

**Comment by zuri-yi** [comment]
@amitshekhariitbhu  thank your

**Comment by thanhniencung** [comment]
i have test your library with geneymotion device and it not working

**Comment by yovenny** [comment]
666

**Comment by TizioIncognito** [comment]
Can be usefull also support of more databases in different paths.
Thanks

**Comment by amitshekhariitbhu** [comment]
Upcoming release, we will add these feautes

**Comment by amitshekhariitbhu** [comment]
Released new version with this feature.
