### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by codebymikey** [amitshekhariitbhu/Android-Debug-Database#10]
```
java.lang.NullPointerException: Attempt to get length of null array
  at com.amitshekhar.server.ClientServer.getDBList(ClientServer.java:412)
  at com.amitshekhar.server.ClientServer.handle(ClientServer.java:216)
  at com.amitshekhar.server.ClientServer.run(ClientServer.java:128)
  at java.lang.Thread.run(Thread.java:818)
```
The culprit seems to be the [following line](https://github.com/amitshekhariitbhu/Android-Debug-Database/blob/v0.2.0/debug-db/src/main/java/com/amitshekhar/server/ClientServer.java#L412).

`mDatabaseDir.list()` is returning null because 

> If this abstract pathname does not denote a directory, then this method returns null.

https://docs.oracle.com/javase/7/docs/api/java/io/File.html#list()

Although unlikely to happen (if you're choosing to use this library, you probably already have the database ready), it would be nicer if it could handle the edge-case accordingly.

**Comment by amitshekhariitbhu** [comment]
Sure I will correct it.

**Comment by codebymikey** [comment]
Thanks for looking into this, but the bug is because `mDatabaseDir.list()` returns a null rather than `mDatabaseDir` being null.

**Comment by amitshekhariitbhu** [comment]
ok I will look again into it
