### ISSUE TITLE
It said "Open http://0.0.0.0.8080/ in your browser"

### ISSUE THREAD

**Issue by mmavis** [amitshekhariitbhu/Android-Debug-Database#100]
I could install the apk in my device successfully, but it said "Open http://0.0.0.0.8080/ in your browser". There is indeed domain name resolution error. I don't know how to resolve this issue now. It both happens on emulator and real device..

**Comment by shivthepro** [comment]
Did you try installing it in a emulator try it in a actual device.. I guess this library does not work well with emulators

**Comment by rizkyyoga** [comment]
to debugging database in emulator run following command in the project directory 'adb forward tcp:8080 tcp:8080' then open in browser http://localhost:8080.
this solution based on readme, you should read carefuly.

**Comment by idragon81** [comment]
This is a common error if your device is on mobile data. Your device should be on the same network as your System

**Comment by kdblue** [comment]
if you connected your laptop/computer with android device via wifi or hotspot then , check your internal ip which is connected to your android device .example in my case it was connect with 192.168.43.1:5555 , so i take only ip and follow with port 8080 (192.168.43.1:8080)

**Comment by ashnehete** [comment]
I had the same message appearing for me when I was connected to my laptop using wifi hotspot on my device. I tried (192.168.43.1:8080) as suggested by @kdblue but it turns out my device was rather on (192.168.43.208:8080). So it turns out, your device might be on any IP in the given range.

**Comment by kdblue** [comment]
@ashnehete, it's very to the device to device .192.168.43.1:8080 in my case it may be different in your case, you can check in your pc via ipconfig or ifconfig .

**Comment by bilal-swayamtechlab** [comment]
If you are test in your device make sure your pc and mobile are connect with same network .

**Comment by alwoalwo42gmailcom** [comment]
@Alwo 
![c5a675f4-0001-0004-0000-000001488981_w948_r1 778_fpx30_fpy55 01](https://user-images.githubusercontent.com/97906262/149952750-1e43d0df-0503-4c86-8483-017be935e64c.jpg)

**Comment by sami1112279** [comment]
https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/100
