### ISSUE TITLE
My Database shows empty 

### ISSUE THREAD

**Issue by ananth10** [amitshekhariitbhu/Android-Debug-Database#105]
I am using room to access my database in my app. but all i can see is empty
![gitdb](https://user-images.githubusercontent.com/13381242/36899972-744c96a4-1e47-11e8-9c9a-4ce5afe9ddc5.jpg)

**Comment by amitshekhariitbhu** [comment]
Click on git.db

**Comment by ananth10** [comment]
![db-debug](https://user-images.githubusercontent.com/13381242/36930858-50bfd532-1ed0-11e8-9b5d-512fc37282e6.png)

**Comment by ananth10** [comment]
I have clicked all. but i could not see anything

**Comment by irudayambics** [comment]
I am also facing the same issue. Any solution to it?

**Comment by TallShahawi** [comment]
Yeah me too,
This happens when the records of database are too much
Say larger than 1000 record or something

**Comment by whui-adr** [comment]
Me too, I am running the test app on Android Oreo.

**Comment by LoveqLRC** [comment]
Same issuse

**Comment by ubuntudroid** [comment]
The log says

```
net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
```

**Comment by bjprogrammer** [comment]
same issue. anyone found solution to this?

**Comment by daniele-sartiano** [comment]
Same issue.

**Comment by DawidJamrozy** [comment]
I have occured the same error when i upgraded room version from 1.0.0 to 1.1.0.
At 1.0.0 everything works just fine, the problem is with version 1.1.0, i haven't checked other versions of room.
@amitshekhariitbhu 
@ananth10

**Comment by NirajManjhi** [comment]
![screen shot 2018-05-15 at 4 07 43 pm](https://user-images.githubusercontent.com/24686649/40051961-327b9e26-585a-11e8-8092-6981c5a472b7.png)

I am also facing the same issue. Two days back it was working for me and today it shows empty database.

**Comment by LeoDroidCoder** [comment]
As a temporary workaround you ma downgrade Room to 1.0.0

**Comment by NirajManjhi** [comment]
# Working perfect with both the Room versions (1.0.0 and 1.1.0)

I just commented the following lines which contains proguard  in build.gradle(Module: app)-->buildTypes  and everything started working fine.

I think it was happening because Proguard doesn't allow anyone to see the data inside your app.

buildTypes {
    debug {
            debuggable true
//            minifyEnabled true
//            shrinkResources true
//            useProguard true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
}

**Comment by saiimons** [comment]
Same issue here with room 1.1.0 and same logs as https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/105#issuecomment-383305447

**Comment by saiimons** [comment]
Found that if the Room DB is built using ```.setJournalMode(TRUNCATE)```, it works perfectly.

This means that the write-ahead logging data breaks the library.

**Comment by DawidJamrozy** [comment]
@saiimons 
It worth to mention that method .setJournalMode() was added after version 1.0.0 so You'll have to upgrade room version in your gradle file in order to use it.

**Comment by saiimons** [comment]
@DawidJamrozy As the issue seems to be appearing with 1.1.0, people using 1.0.0 won't have to do this. 
See :
![image](https://user-images.githubusercontent.com/6832416/40182600-c0d3530c-59b9-11e8-9540-f8b5b121885b.png)
 
@ananth10 @irudayambics @TallShahawi @whui-adr @LoveqLRC @ubuntudroid @bjprogrammer @daniele-sartiano see my previous comment for a solution.

@amitshekhariitbhu you may add a try catch when opening a DB file, with proper error handling, this could prevent the server from crashing.

**Comment by amitshekhariitbhu** [comment]
@saiimons I will consider your suggestion.

**Comment by NirajManjhi** [comment]
Again I am facing the same issue. Please resolve it so that our development will be seamless. We are taking help of this library. Please help.

**Comment by NirajManjhi** [comment]
I was getting the same SqliteException as mentioned above and my database was showing empty. I have done minor config changes and everything working absolutely fine now. Please find the configuration below:

Room Persistence Library
implementation 'android.arch.persistence.room:runtime:1.1.1-rc1'
annotationProcessor "android.arch.persistence.room:compiler:1.1.1-rc1"

Android-Debug-Database
debugImplementation 'com.amitshekhar.android:debug-db:1.0.1' (Changed from 1.0.3 to 1.0.1) as mentioned in official Mindorks blog (https://blog.mindorks.com/debugging-android-databases-and-shared-preferences-in-the-easiest-way-e5f705dfc06b)

build.gradle (Module app)
buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
//            minifyEnabled false
//            useProguard false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

MainDatabase.java
Room.databaseBuilder(context.getApplicationContext(),
                            MainDatabase.class, AppConstants.DATABASE_NAME)
                            .fallbackToDestructiveMigration()
                            .setJournalMode(TRUNCATE)
                            .build();


![screen shot 2018-06-18 at 4 30 44 pm](https://user-images.githubusercontent.com/24686649/41532524-00bcc2ea-7315-11e8-8b0a-5312bb96c6f6.png)

**Comment by eriknyk** [comment]
I've used Facebook's Stheto http://facebook.github.io/stetho/  , pretty good because it uses the chrome devtools as interface
