### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by frkmed** [amitshekhariitbhu/Android-Debug-Database#108]
Hello,
I face this issue where i using this library with google Room orm
03-17 10:15:22.554 6843-6864/com.test E/SQLiteLog: (26) file is encrypted or is not a database
03-17 10:15:22.555 6843-6864/com.test E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/com.test/databases/test.db-wal
03-17 10:15:22.555 6843-6864/com.test E/DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/com.test/databases/test.db-wal

**Comment by wushexu** [comment]
I encountered similar problem.  It seems like something wrong in supporting sqlite in WAL mode.  After I configured the db to JOURNAL mode, every thing was ok. Like this:
```
Room.databaseBuilder(app, xxxDB.class, "xxx.db")
                .setJournalMode(RoomDatabase.JournalMode.TRUNCATE).build()
```

**Comment by ArcDexx** [comment]
@wushexu Your answer does solve the problem for me as well. However, did you notice any drawback to using TRUNCATE over WIRTE_AHEAD_LOGGING ? From what I could find, there are pros and cons to using WAL, see [this link](https://www.sqlite.org/wal.html) for more info.
