### ISSUE TITLE
Create Table interactively?

### ISSUE THREAD

**Issue by hanct** [amitshekhariitbhu/Android-Debug-Database#113]
Hi, does Android-Debug-Database provide the possibility to create table interactively via the browser?

**Comment by amitshekhariitbhu** [comment]
@hanct yes, we can work on it. Looks good to me.

**Comment by amitshekhariitbhu** [comment]
currently you can just run query

**Comment by hanct** [comment]
Thanks! 

Sidenote: Via my android program,  I am able to save records into my table, and even select the count  to ensure the count increase for each record I save into. On the webpage, i saw my database listed , however when i click, i saw no tables listed out. Do  i need to enter any query to list out the table(s) in the database?

**Comment by hanct** [comment]
By the way, I am working in
