### ISSUE TITLE
support room 1.1.0

### ISSUE THREAD

**Issue by balintsteinbach** [amitshekhariitbhu/Android-Debug-Database#115]
It is not possible to browse a database created with room 1.1.0.

Works fine with Room 1.0.0

**Comment by amitshekhariitbhu** [comment]
I will check

**Comment by balintsteinbach** [comment]
I have to add these dependencies to start my application:
    implementation "android.arch.persistence.room:runtime:1.1.0"

After that, I can select the database in the browser but the lines are not there. 

This is the exception:

> E/ClientServer: Exception.
>                 net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
>                     at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
>                     at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
>                     at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
>                     at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
>                     at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
>                     at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
>                     at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
>                     at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
>                     at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
>                     at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
>                     at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
>                     at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
>                     at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1065)
>                     at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1226)
>                     at com.amitshekhar.server.RequestHandler.openDatabase(RequestHandler.java:185)
>                     at com.amitshekhar.server.RequestHandler.getTableListResponse(RequestHandler.java:304)
>                     at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:113)
>                     at com.amitshekhar.server.ClientServer.run(ClientServer.java:76)
>                     at java.lang.Thread.run(Thread.java:818)

**Comment by LoneDev6** [comment]
Same problem

**Comment by qstuff** [comment]
I encountered the same issue. I hope there will be an update.
I like this tool very much, used Stetho before but Stetho has too much features. For simply debugging dbs it's too inconvenient.

**Comment by kldMohammed** [comment]
i use room with kotlin and when add library to gradle give me this 


**_error: AppDatabase_Impl is not abstract and does not override abstract method clearAllTables() in RoomDatabase_**

**Comment by mukarramali** [comment]
Not showing room database.
`debugImplementation 'com.amitshekhar.android:debug-db:1.0.4'
 implementation 'android.arch.persistence.room:runtime:1.1.0'`

**Comment by mukarramali** [comment]
It worked. Thanks @amitshekhariitbhu  for this amazing tool

**Comment by MohadFarhan** [comment]
@kldMohammed  i just solved the same problem. If you are using 
`implementation "android.arch.persistence.room:runtime:1.0.0` runtime version then add this configuration line below(end of) app.gradle file 

`configurations.all {
    resolutionStrategy.force 'android.arch.persistence.room:runtime:1.0.0'
}` 


change runtime version based on what version you are using.
This has solved similar problem.
