### ISSUE TITLE
Unable to view tables in database

### ISSUE THREAD

**Issue by hanct** [amitshekhariitbhu/Android-Debug-Database#116]
Via my android program,  I am able to save records into my table, and even select the count  to ensure the count increase for each record I save into. 
using the android-debug-database webpage, i saw my database listed , however when i click on it, i saw no tables listed out.  
My queries are:
1) I am using emulator. Or do i have to use a real phone?
2) I create a database called "simplytask". But i also saw 2 extra database "simplytaskase-shm" and "simplytask-wal", which I am sure i did not create them. Any idea if these are autocreated by Android-Debug-Database??

**Comment by idragon81** [comment]
This is the same issue as #115
The Library does not yet support the changes made in Room 1.1.0

**Comment by amitshekhariitbhu** [comment]
@hanct Please try the new version
`debugImplementation 'com.amitshekhar.android:debug-db:1.0.4'`
