### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by choxxy** [amitshekhariitbhu/Android-Debug-Database#129]
Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.amitshekhar.android:debug-db:1.0.4.

**Comment by amitshekhariitbhu** [comment]
Please refer [this link](https://stackoverflow.com/questions/46949622/android-studio-3-0-unable-to-resolve-dependency-for-appdexoptions-compileclas) and check if it can help us here.

**Comment by choxxy** [comment]
I was working offline, going online solved my problem. Refered to the link  provided by amitshekhariitbhu above
