### ISSUE TITLE
Apk size huge increase after adding SqlCipher support (v1.0.2+)

### ISSUE THREAD

**Issue by androideveloper** [amitshekhariitbhu/Android-Debug-Database#142]
After upgrading to latest version, apk size is increased by 13MB .so files, that ,as I guess, are used to support SqlCipher. Is there a way to exclude it?

**Comment by amitshekhariitbhu** [comment]
This library is not meant to include in production. There should be a way to remove it in debug also. I will add support for that in the upcoming release.

**Comment by androideveloper** [comment]
We don't include it in production (only debugImplementation). But CI server uses the same assembleDebug and produces larger .apk files if I upgrade to latest. I guess, that will help us to remove in CI debug builds without introducing separate build type or flavor

**Comment by amitshekhariitbhu** [comment]
Agreed. We will solve it.

**Comment by amitshekhariitbhu** [comment]
@androideveloper solved
### Using Android Debug Database Library in your application

Add this to your app's build.gradle

```groovy
debugImplementation 'com.amitshekhar.android:debug-db:1.0.5'
```

Using the Android Debug Database with encrypted database

```groovy
debugImplementation 'com.amitshekhar.android:debug-db-encrypt:1.0.5'
```

**Comment by androideveloper** [comment]
@amitshekhariitbhu Thanks, it saves ~8MB on every build! But it seems that something is broken with querying. 
`select * from CUSTOMERS` returns list of customers, but `select fNAME from CUSTOMERS` return nothing. Chrome Version 72.0.3626.109 (Official Build) (64-bit). Tried also on Edge, the same there.

**Comment by amitshekhariitbhu** [comment]
@androideveloper Can you please create a separate issue for that so that we track and fix that too.

**Comment by androideveloper** [comment]
https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/147
