### ISSUE TITLE
Query doesn't work properly

### ISSUE THREAD

**Issue by androideveloper** [amitshekhariitbhu/Android-Debug-Database#147]
`select * from CUSTOMERS` returns list of customers, but `select fNAME from CUSTOMERS` return nothing. Chrome Version 72.0.3626.109 (Official Build) (64-bit). Tried also on Edge, the same there. 
Version 1.0.5.

**Comment by amitshekhariitbhu** [comment]
@androideveloper Thanks for pointing it out. I have fixed it in the new version

### Using Android Debug Database Library in your application

Add this to your app's build.gradle

```groovy
debugImplementation 'com.amitshekhar.android:debug-db:1.0.6'
```

Using the Android Debug Database with the encrypted database

```groovy
debugImplementation 'com.amitshekhar.android:debug-db-encrypt:1.0.6'
```

**Comment by androideveloper** [comment]
Thanks! It works!
