### ISSUE TITLE
Relayout navigation to breadcrumbs UX pattern

### ISSUE THREAD

**Issue by yshubin** [amitshekhariitbhu/Android-Debug-Database#17]
Hi Amit,

What you think about changing navigation to breadcrumbs UX pattern (something like [Home] -> [Database] -> [Table] in the top of the screen with popups for database or table selection)? 

![breadcrumbs](https://cloud.githubusercontent.com/assets/6691617/20687311/0c6ba46e-b5cd-11e6-9335-9325050f2944.jpg)

So it gives more spacing for content of tables with more than several columns (my case :) )

**Comment by amitshekhariitbhu** [comment]
@yshubin LGTM, agreed with you. We can proceed on this.
