### ISSUE TITLE
Empty realisation for release build

### ISSUE THREAD

**Issue by GrishinSergey** [amitshekhariitbhu/Android-Debug-Database#180]
Hello.

First of all, thank you for your lib. It is really helps us with debuggind database. My issue not a bug but. maybe improvement. Can you made stub implementation of this lib for release build?
Cuz for now our flow is pretty like this:
- test debug build by developers.
- comment line with initialisation of lib
- building release app.

Will be cool to have stub for release build, where is no any server started. Just for simplify build process.

**Comment by amitshekhariitbhu** [comment]
That's why it is suggested to use `debugImplementation` and for simple use, you do not need to call any method.
In case if you are calling any method, we have provided a reflection way to do so.

**Comment by GrishinSergey** [comment]
I didn't saw this variant. Ok. I tried, and it is work for me. I will close this issue
