### ISSUE TITLE
Question: can it handle apps without changing their code?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [amitshekhariitbhu/Android-Debug-Database#20]

**Comment by amitshekhariitbhu** [comment]
There is no need of changing the code of your application.

Thanks
Amit Shekhar

**Comment by AndroidDeveloperLB** [comment]
So I guess it requires root? In order to access protected files...
right?

**Comment by amitshekhariitbhu** [comment]
If you have to use any library, you must add that as a dependency. So, there is no need of root.

Thanks
Amit Shekhar

**Comment by AndroidDeveloperLB** [comment]
Adding dependency meaning changing code, as it adds it to the app, which
also means I have to have the app open sourced to me.
Doesn't adding the dependency add code to the app?
Is it possible to use it on any app, even those that don't have this
dependency?

**Comment by amitshekhariitbhu** [comment]
Try to use it first, you will get the idea how it works
