### ISSUE TITLE
JCenter is shutting down 

### ISSUE THREAD

**Issue by makvasic** [amitshekhariitbhu/Android-Debug-Database#208]
JCenter is getting shut down in May https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by sebasira** [comment]
Right now jCenter is down, I think it hast to be an error... where else can we find it?

**Comment by sebasira** [comment]
I'm using jitpack!

https://jitpack.io/#amitshekhariitbhu/Android-Debug-Database/v1.0.6

**Comment by Will5** [comment]
I already have jitpack.io in my project, but for some reason Android-Debug-Database is not working when I remove jcenter from the project. It looks like jitpack.io may be returning a 403 Forbidden? I might try it with an empty project later, but I also tried moving jitpack.io to the top and had the same result.

**Comment by sebasira** [comment]
You need to change the way you declare your dependency, when using jitpack. In this case it's like:

```groovy
implementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:v1.0.6'
```

**Comment by Will5** [comment]
Thanks, you are right; I missed the addition of `.Android-Debug-Database` 🙂

**Comment by Sayum24** [comment]
Maybe update the readme then.

**Comment by Boxroma** [comment]
> ```groovy
> 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:v1.0.6'
> ```

It would be great to have the readme updated. Save someone else the hustle..

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7")
```

Using the Android Debug Database with encrypted database

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7")
```

And to provide the password for the DB, you should add this in the Gradle:
DB_PASSWORD_{VARIABLE}, if for example, PERSON is the database name: DB_PASSWORD_PERSON
```groovy
debug {
    resValue("string", "DB_PASSWORD_PERSON", "password")
}
```
