### ISSUE TITLE
move library to mavenCentral

### ISSUE THREAD

**Issue by niketkn** [amitshekhariitbhu/Android-Debug-Database#212]
since jCenter() has shut down, I request you to move this library to mavenCentral or other repo

**Comment by mhrohani1385** [comment]
I strongly agree , really annoying !

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7")
```

Using the Android Debug Database with encrypted database

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7")
```

And to provide the password for the DB, you should add this in the Gradle:
DB_PASSWORD_{VARIABLE}, if for example, PERSON is the database name: DB_PASSWORD_PERSON
```groovy
debug {
    resValue("string", "DB_PASSWORD_PERSON", "password")
}
```
