### ISSUE TITLE
Please move your library to mavencentral jcenter is not longer available

### ISSUE THREAD

**Issue by vhernandezvitu** [amitshekhariitbhu/Android-Debug-Database#216]
Since jcenter is down people who use your library cannot compile

**Comment by arunkrishnakv** [comment]
+1. Even though your particular library is available in maven repository, some of your dependencies are using jcenter. Could you please update those?  

```
\--- com.amitshekhar.android:debug-db:1.0.6 FAILED
+--- com.amitshekhar.android:debug-db:1.0.6 FAILED
+--- com.amitshekhar.android:debug-db:1.0.6 FAILED
|    |    +--- com.android.volley:volley:1.1.1 FAILED
|    |    |    +--- com.facebook.yoga:proguard-annotations:1.14.1 FAILED
|    |    |    \--- com.facebook.fbjni:fbjni-java-only:0.0.3 FAILED
+--- com.amitshekhar.android:debug-db:1.0.6 FAILED

```

These were the problematic libraries I could find. Thanks a ton for your amazing library.

**Comment by powell** [comment]
+1
Please, please. Your library is great !

**Comment by huhuang03** [comment]
+1
```
Could not find com.amitshekhar.android:debug-db:1.0.6.
Required by:
    project :app
Search in build.gradle files
```

**Comment by CleatonPais** [comment]
+1

Really helpful library. Please migrate

**Comment by quillalady** [comment]
Please, migrate

**Comment by ajinkya-iam** [comment]
Please following steps to import this lib

### Step 1. Add the JitPack repository to your build file
```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
### Step 2. Add the dependency
```
dependencies {
	        implementation 'com.github.amitshekhariitbhu:Android-Debug-Database:Tag'
	}
```
**Reference** - https://www.jitpack.io/#amitshekhariitbhu/Android-Debug-Database/v1.0.6

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7")
```

Using the Android Debug Database with encrypted database

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7")
```

And to provide the password for the DB, you should add this in the Gradle:
DB_PASSWORD_{VARIABLE}, if for example, PERSON is the database name: DB_PASSWORD_PERSON
```groovy
debug {
    resValue("string", "DB_PASSWORD_PERSON", "password")
}
```
