### ISSUE TITLE
Could not resolve com.amitshekhar.android:debug-db:1.0.6.

### ISSUE THREAD

**Issue by aneebali** [amitshekhariitbhu/Android-Debug-Database#236]
> Could not resolve com.amitshekhar.android:debug-db:1.0.6.
     Required by:
         project :app
      > Could not resolve com.amitshekhar.android:debug-db:1.0.6.
         > Could not get resource 'https://jitpack.io/com/amitshekhar/android/debug-db/1.0.6/debug-db-1.0.6.pom'.
            > Could not HEAD 'https://jitpack.io/com/amitshekhar/android/debug-db/1.0.6/debug-db-1.0.6.pom'. Received status code 401 from server: Unauthorized

**Comment by amitshekhariitbhu** [comment]
Solution:

Add this in your `settings.gradle`:
```groovy
maven { url 'https://jitpack.io' }
```

If you are using `settings.gradle.kts`, add the following:
```kotlin
maven { setUrl("https://jitpack.io") }
```

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db:1.0.7")
```

Using the Android Debug Database with encrypted database

Add this in your `build.gradle`
```groovy
debugImplementation 'com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7'
```

If you are using `build.gradle.kts`, add the following:
```kotlin
debugImplementation("com.github.amitshekhariitbhu.Android-Debug-Database:debug-db-encrypt:1.0.7")
```

And to provide the password for the DB, you should add this in the Gradle:
DB_PASSWORD_{VARIABLE}, if for example, PERSON is the database name: DB_PASSWORD_PERSON
```groovy
debug {
    resValue("string", "DB_PASSWORD_PERSON", "password")
}
```

**Comment by aneebali** [comment]
Thanks
