### ISSUE TITLE
How can i use this in my project, which is not a Android studio project?

### ISSUE THREAD

**Issue by singlepig** [amitshekhariitbhu/Android-Debug-Database#26]
Hi, guys! Please help!
For me, my project is not AS(Android Studio) project and is not complied by gradle. It's an android source code project complied with `Android.mk`. And I don't have right to update the project to android studio project.
I cloned the code and complied it, now I have `debug-db-debug.arr` and `debug-db-release.aar`. I can add aar file into `Android.mk` as static lib, but what should I do in my java code? 
What should I import and how to init DebugDB? port ?

**Comment by amitshekhariitbhu** [comment]
You don't have to do anything in Java code. It is an auto-initialize library.

**Comment by singlepig** [comment]
@amitshekhariitbhu Thanks for answering! I just cp `debug-db-debug.arr` to my project's folder `libs/debug-db`, and add the following code into `Android.mk`:
```
LOCAL_STATIC_JAVA_LIBRARIES += debug-db
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := debug-db:libs/debug-db/debug-db-debug.aar
```
Then, I compile with command `mm`. After I install my app in my phone, there is no output like `D/DebugDB: Open http://XXX.XXX.X.XXX:8080 in your browser`in `adb logcat`

I think you said it's an auto-initialize library means gradle will initialize it for user, but I'm not using gradle and I can't use gradle. All I want to know is how can I initialize it by myself, in activity's onCreate or other place. 
Please look at this repo: https://github.com/skyhacker2/SQLiteOnWeb-Android
In it's `Setup` section, users can initialize it in java code.

**Comment by amitshekhariitbhu** [comment]
@singlepig Check the link https://medium.com/@andretietz/auto-initialize-your-android-library-2349daf06920#.q7lxebdi6
you will get the idea, the library itself call that function
