### ISSUE TITLE
Integer overflow?

### ISSUE THREAD

**Issue by Maragues** [amitshekhariitbhu/Android-Debug-Database#27]
Large INTEGER columns seem to overflow, showing negative number instead of the real value

```
sqlite> .schema user
CREATE TABLE USER (
id INTEGER PRIMARY KEY AUTOINCREMENT,
createdAt INTEGER NOT NULL,
  ...
```

Pulling the *.db* manually and querying

```
sqlite> select createdAt from user where id=112;
createdAt
1480519860000
```

*DebugDB* shows that same cell with value *-1243857120*

**Comment by amitshekhariitbhu** [comment]
Thanks for pointing the issue, I will go through it and fix it.

Thanks
Amit Shekhar

**Comment by amitshekhariitbhu** [comment]
Fixed
