### ISSUE TITLE
Not Working on Genymotion

### ISSUE THREAD

**Issue by elsennov** [amitshekhariitbhu/Android-Debug-Database#30]
Hi, it is not working on my end. It keeps loading the web page. It is said in the log:

```
D/DebugDB: Open http://10.0.3.15:8081 in your browser
```

But it was loading then said that the site can't be reached. Is there anything wrong?
FYI, i use kotlin and there is no java folder inside src. Another info:
- Min sdk is 15
- Compile sdk is 25
- build tools version 25.0.0
- target sdk 25
- tested on Genymotion 4.1.1

Please help, thanks!

**Comment by amitshekhariitbhu** [comment]
@elsennov Your phone(try with phone once) and laptop should be on the same wifi. Meanwhile I will test it with Genymotion.

**Comment by elsennov** [comment]
It works like a charm on the phone. I will update the title to be specific on genymotion only.

**Comment by shaunidiot** [comment]
Pretty sure it's problems with emulator similar to another question on the issue page.

Try using the command 
`adb forward tcp:8080 tcp:8080`

From: 
https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/6#issuecomment-262288856

**Comment by hyperax** [comment]
@elsennov Do you use bridge in virtual device's settings?

DebugDB is working very well with "Bridge". I've tested.

**Comment by amitshekhariitbhu** [comment]
@elsennov The solution provided by @hyperax work well.
For Genymotion, enable bridge from configure virtual device (option available in genymotion)

**Comment by elsennov** [comment]
@amitshekhariitbhu @hyperax thanks for the solution!
