### ISSUE TITLE
Display wrong value with the database

### ISSUE THREAD

**Issue by maphongba008** [amitshekhariitbhu/Android-Debug-Database#32]
I saved the value 1484730253154 in the database, and open browser, it display -1328431262.
![screen shot 2017-01-18 at 4 18 35 pm](https://cloud.githubusercontent.com/assets/8359203/22057991/d3cba862-dd99-11e6-911a-b2a8007fc2ae.png)

**Comment by amitshekhariitbhu** [comment]
we have fixed the issue that is in development, we will add this in the new release.

**Comment by maphongba008** [comment]
Good work (y)

**Comment by amitshekhariitbhu** [comment]
Fixed in new version
