### ISSUE TITLE
Can't see custom database location?

### ISSUE THREAD

**Issue by htooaunghlaing** [amitshekhariitbhu/Android-Debug-Database#33]
It seems you take DBs from com.package.packagename/databases/
My DB location is in com.package.packagename/files/myfolder/mydatabase.db .
So, How can I see for custom database. Thanks

**Comment by amitshekhariitbhu** [comment]
We will try to add the feature of adding the custom path in the new release.

Thanks
Amit Shekhar

**Comment by htooaunghlaing** [comment]
Thanks, let me know if that features avaliable .

**Comment by amitshekhariitbhu** [comment]
Released new version with this feature.
