### ISSUE TITLE
Pragma doesn't work

### ISSUE THREAD

**Issue by Boza-s6** [amitshekhariitbhu/Android-Debug-Database#37]
Hi,

If I try to execute query like `PRAGMA table_info(myTable);` I'll get error.
Root cause is in DatabaseHelper class in method executeQueryAndGetResponse.
It checks if first word in query is "select" and does query otherwise does execSql which doesn't support results.

I think this could be solved by checking for "pragma" as well and in that case executing "getTableInfo" method.

**Comment by amitshekhariitbhu** [comment]
@Boza-s6 Yes you are correct, will add this in new release

**Comment by vinayagasundar** [comment]
@amitshekhariitbhu I've implemented this feature in my development branch. 
I'll create PR soon.

**Comment by Boza-s6** [comment]
Great, thanks!

**Comment by amitshekhariitbhu** [comment]
Released new version with this feature.
