### ISSUE TITLE
Can not run Android Project because duplicate entry gson.

### ISSUE THREAD

**Issue by aheadlcx** [amitshekhariitbhu/Android-Debug-Database#39]
The log as follows:
Error:Execution failed for task ':transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/gson/Gson$1.class

**Comment by amitshekhariitbhu** [comment]
Please refer the following solution
http://stackoverflow.com/questions/40240414/how-to-solve-java-util-zip-zipexception-duplicate-entry-com-google-gson-annotat

**Comment by aheadlcx** [comment]
@amitshekhariitbhu Thanks a lot.
