### ISSUE TITLE
How can I contribute to this repository?

### ISSUE THREAD

**Issue by daveRanjan** [amitshekhariitbhu/Android-Debug-Database#41]
Hi, I am Devendra, a Java Developer and Android Enthusiast, I have used this library in one of my android projects and its great. I want to be part of development. Let me know, how can I do it?

**Comment by amitshekhariitbhu** [comment]
We will always welcome your pull request in the development branch. Think of a feature that you think is missing in the library. Create an issue for that feature and discuss there and build it and make pull request.

Thanks
Amit Shekhar
