### ISSUE TITLE
If there is a subdirectory in /data/data/myapp/databases, than it doesn't work

### ISSUE THREAD

**Issue by ArcherCX** [amitshekhariitbhu/Android-Debug-Database#43]
It just throw an exception like this :

E/SQLiteLog: (14) cannot open file at line 30058 of [9491ba7d73]
E/SQLiteLog: (14) os_unix.c:30058: (21) open(/data/data/myapp/databases/cc) - 
E/SQLiteConnection: DB info: sqlite3_open_v2, path: /data/data/myapp/databases/cc, flag: 6, ret: 14
E/SQLiteConnection: DB info: errno = 21, errno message = Is a directory
E/SQLiteDatabase: Failed to open database '/data/data/myapp/databases/cc'.

Although I can open the web,  it only show databases's name, you can't see the data.
It seems the lib deals with dir as a database, and cause everything broken after.

**Comment by amitshekhariitbhu** [comment]
We will add this support sooner

**Comment by amitshekhariitbhu** [comment]
Now you can pass the custom path to the library.
