### ISSUE TITLE
 http://0.0.0.0:8080 is shown for real phone

### ISSUE THREAD

**Issue by jordenchang55** [amitshekhariitbhu/Android-Debug-Database#44]
When I use my smart phone as AP and let my laptop connect to it, the link will be `http://0.0.0.0:8080` and it cannot show anything.

The simplest solution I found is change the URL to router's ip address, for example, `http://192.168.1.1:8080`, and then it will work. Can you make the address show in the logcat?

**Comment by amitshekhariitbhu** [comment]
Let me check the issue.

Thanks
Amit Shekhar
