### ISSUE TITLE
Unable to view database of more then one app?

### ISSUE THREAD

**Issue by adnansattar09** [amitshekhariitbhu/Android-Debug-Database#46]
Hi Amit thanks for such an awesome tool, its really helping. i am developing multiple apps with v 1.0.0, unable to view databases of more then one application.

**Comment by amitshekhariitbhu** [comment]
Use different port number for different app
```
debug {
    resValue("string", "PORT_NUMBER", "8081")
}
```

**Comment by adnansattar09** [comment]
Oh! great thanks your such a nice one.

**Comment by mani-smartek21** [comment]
Hi @amitshekhariitbhu 

Not working Different Port 

        resValue("string", "PORT_NUMBER", "8085")
