### ISSUE TITLE
I can see the datas in the browser  of my phone, but can not in my computer

### ISSUE THREAD

**Issue by haofei91** [amitshekhariitbhu/Android-Debug-Database#5]
I can see the datas in the browser  of my phone, but can not in my computer. with the same url.

is any trouble with my wifi?   I use the company's wifi

**Comment by samvidmistry** [comment]
I guess your computer would be connected with LAN and your phone is actually connected to WiFi, please make sure that they both are in same network.

**Comment by haofei91** [comment]
Yeah, you are right.     
 
Actually,  when i make two phones in the same WIFI, I can get it in both phones.
But,  in the office,  I can not make my computer connect with the same wifi, which is only can be connected with the LAN.

Thus, I think I also need Android-Debug-Database supported with the USB.

A useful project

**Comment by amitshekhariitbhu** [comment]
To be added in new release https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/4
