### ISSUE TITLE
Use a dynamic layout to avoid horizontal scrolling

### ISSUE THREAD

**Issue by tobiasschuerg** [amitshekhariitbhu/Android-Debug-Database#50]
The data column should fit the full width.

Right now only about 4-5 columns can be shown and if there are more columns in a table horizontal scrolling is needed although there is plenty of room left.

The simplest solution is to just remove the senseless padding in https://github.com/amitshekhariitbhu/Android-Debug-Database/blob/2538f9d4882ba317c5a61f8185ff98a6cab6c446/debug-db/src/main/assets/index.html#L113

**Comment by amitshekhariitbhu** [comment]
Good Suggestion 👍

**Comment by ozmium** [comment]
There is a pull request that helps to fix this by reducing the amount of horizontal scrolling: https://github.com/amitshekhariitbhu/Android-Debug-Database/pull/78
