### ISSUE TITLE
The log info is :  D/DebugDB: Open http://0.0.0.0:8080 in your browser

### ISSUE THREAD

**Issue by lhlhlh111000** [amitshekhariitbhu/Android-Debug-Database#6]
what's worry with me, i can not open the database…

**Comment by amitshekhariitbhu** [comment]
r u trying this with emulator ?

**Comment by lhlhlh111000** [comment]
@amitshekhariitbhu  yes

**Comment by amitshekhariitbhu** [comment]
@lhlhlh111000  I need to fix the issue happening with emulator.

**Comment by vinayagasundar** [comment]
@lhlhlh111000 @amitshekhariitbhu I don't think we can control emulator IP address by code. but my simple solution for this is
In terminal  
`adb forward tcp:8080 tcp:8080`

Open browser with http://localhost:8080

**Comment by amitshekhariitbhu** [comment]
@vinayagasundar thanks for the info. Will try it soon

**Comment by lonnnyzhang** [comment]
@vinayagasundar It works!

**Comment by pratikbutani** [comment]
I am getting same problem. @amitshekhariitbhu

**Comment by lorenzos** [comment]
@vinayagasundar workaround works for me too, but please @amitshekhariitbhu try to make it work with emulators too. Using the default Android Studio emulators is the default option while developing, and it's incredibly faster than using real devices. Plus, after API 23 is not possible to use the Android Device Monitor to pull the DB files from the emulator device, so your debugger is practically the only available tool we have to inspect our data!

**Comment by amitshekhariitbhu** [comment]
@lorenzos sure sure... we will fix it in new release.

**Comment by Yadav-Sunil** [comment]
not open database in andriod device

**Comment by Aexyn** [comment]
I am getting it on Real device too. 
Android version: 6.0
Android device model: XT1092

**Comment by amitshekhariitbhu** [comment]
@Aexyn Your device was connected to wifi when you first started the app?

**Comment by Aexyn** [comment]
@amitshekhariitbhu No.. It is connected to desktop the whole time

**Comment by Aexyn** [comment]
Also it was unable to show the my database as I have a custom path where I store them

**Comment by richdyang** [comment]
+1

**Comment by guyulmaz** [comment]
I work at android studio 3.0 canary 1
Same error:
05-24 12:44:14.270 14660-14660/...D/DebugDB: Open http://0.0.0.0:8080 in your browser
Can you help please.

**Comment by amitshekhariitbhu** [comment]
@guyulmaz  Checking the issue. @vinayagasundar any idea?

**Comment by vinayagasundar** [comment]
@amitshekhariitbhu @guyulmaz I'll check this and let you know.

**Comment by vinayagasundar** [comment]
@guyulmaz are you sure your system & device connected to the same Wifi Network
if you're emulator or using USB please refer  [here]( https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/6#issuecomment-262288856)

@amitshekhariitbhu

**Comment by guyulmaz** [comment]
@vinayagasundar 
I'm using the emulator of android studio, the emulator is Nexus 5 api 24 (Android 7)

**Comment by vinayagasundar** [comment]
@guyulmaz okay please check the work around  [here](https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/6#issuecomment-262288856)

**Comment by guyulmaz** [comment]
@vinayagasundar 

\AppData\Local\Android\sdk\platform-tools>adb forward tcp:8080 tcp:8080
then 
Open browser with http://localhost:8080

it works thanks

**Comment by tang5011235** [comment]
D/DebugDB: Open http://172.17.100.15:8081 in your browser  
it is my Emulator ip,not my laptop ip, i could not open in my browser

**Comment by iraj-wisilica** [comment]
I had the same issue. When switched back to WiFi network from my data connection. Everything seems be working like charm. Good work.

**Comment by irudayambics** [comment]
I had the same issue. When switched back to WiFi network from my data connection everything worked. Good work.

**Comment by ozmium** [comment]
It seems that this happens when the device is using a 3G/4G mobile internet, instead of WiFi. Suggestion: Perhaps the app could detect "0.0.0.0" as a probable error condition and change the message -- something like this:

`D/DebugDB: Open http://0.0.0.0:8080 in your browser. Warning: This address may not work. Ensure your Android device is on the same WiFi network as your computer, then Force Quit and restart the app.`

**Comment by Kisty** [comment]
How about a small gradle plugin which would run `adb forward tcp:8080 tcp:8080` automatically when running an app with the library in the classpath? I guess you could hook in to the install task or something.

**Comment by amitshekhariitbhu** [comment]
@Kisty This is good suggestion.

**Comment by grandgrant** [comment]
i have an issue that error in my room database when use your library. This is the error error: "TransactionDatabase_Impl is not abstract and does not override abstract method clearAllTables() in RoomDatabase". Can you give the solution?

**Comment by garik888** [comment]
Hey. I can not execute a query like this:
SELECT max (day) as max_day FROM statistics
does not show anything at all!

**Comment by ChenglongMa** [comment]
> @lhlhlh111000 @amitshekhariitbhu I don't think we can control emulator IP address by code. but my simple solution for this is
> In terminal
> `adb forward tcp:8080 tcp:8080`
> 
> Open browser with http://localhost:8080

This tip works for me, just reminding that: 
For real smartphone, http://0.0.0.0:8080 works on **Mac OS**, while http://localhost:8080 works on **Win OS**.
Thanks :)

**Comment by nilsi** [comment]
I had the same issue. But looking up the tablets IP and trying with that still worked.

**Comment by fahmieshaq** [comment]
Turn on your Wifi
