### ISSUE TITLE
Query results are not displayed in 1.0.1 any more

### ISSUE THREAD

**Issue by ikravchenko** [amitshekhariitbhu/Android-Debug-Database#66]
if you select a table and try to run a custom query like e.g. "SELECT name from SOME_TABLE", no results are shown on the right. In 0.5.0  feature worked. Please fix

**Comment by amitshekhariitbhu** [comment]
@ikravchenko Let me check the issue and fix it.

**Comment by vinayagasundar** [comment]
@ikravchenko are you sure selected database have the table which you're querying ? It'll be more help full if you can share the log from Logcat..

**Comment by fajarpnugroho** [comment]
it's happend on me. If you doing `select` with specific `field`, e.g `SELECT id, name FROM table`. But If you doing without specific `field` e.g`SELECT * FROM table` is work fine.
