### ISSUE TITLE
Can I use this lib to view a db file?

### ISSUE THREAD

**Issue by CoXier** [amitshekhariitbhu/Android-Debug-Database#67]
As title says, can I use this lib to view a db file?

**Comment by vinayagasundar** [comment]
@CoXier  yes

**Comment by CoXier** [comment]
Is there any doc?

**Comment by vinayagasundar** [comment]
Can you check the [README](https://github.com/amitshekhariitbhu/Android-Debug-Database/blob/master/README.md)

**Comment by CoXier** [comment]
I just want view and do not import this lib to my porject.

**Comment by vinayagasundar** [comment]
Yes that's how this libs designed.
In android gradle dependency 

`debugCompile 'com.amitshekhar.android:debug-db:1.0.1'` 

add the above line

**Comment by CoXier** [comment]
No I do not want to `debugCompile` yet.Just open a db file and view it.

**Comment by vinayagasundar** [comment]
I didn't understand your context clear ? Can you explain more details

**Comment by CoXier** [comment]
Yes,for example I have a file called `test.db` now I want to view its content.No debug,no edit just view it.

**Comment by vinayagasundar** [comment]
So you created  db inside a Android application right ?

**Comment by gitanshu** [comment]
@CoXier If you want to open a .db file on your computer, use some sqlite viewer like sqlitebrowser.org/ or inloop.github.io/sqlite-viewer/ or just google `sqlite viewer` and you'll find plenty.
Or you can directly connect to the db file in your phone by following this: https://stackoverflow.com/a/18280430/2829308

This library makes it much much easier though and you should try it.
