### ISSUE TITLE
No data shown on the panel and Exception

### ISSUE THREAD

**Issue by KonradSzewczuk** [amitshekhariitbhu/Android-Debug-Database#72]
I have a problem with showing the data of the emulator.

I was following those steps:
- i added the dependency
- i made this: adb forward tcp:8080 tcp:8080 in my terminal
- after that i was able to see the panel at: http://localhost:8080

But when i go to this address it shows just nothing, but a blank panel with no data:
![debug-database](https://user-images.githubusercontent.com/9077038/28749665-26f30374-74cf-11e7-8d93-287a28e9bef5.png)

I also get this Exception:
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
07-30 00:31:54.978 16077-16159/com.okset.realmsample W/System.err:     at com.amitshekhar.utils.DatabaseHelper.getTableData(DatabaseHelper.java:83)
07-30 00:31:54.979 16077-16159/com.okset.realmsample W/System.err:     at com.amitshekhar.server.RequestHandler.executeQueryAndGetResponse(RequestHandler.java:235)
07-30 00:31:54.979 16077-16159/com.okset.realmsample W/System.err:     at com.amitshekhar.server.RequestHandler.handle(RequestHandler.java:118)
07-30 00:31:54.979 16077-16159/com.okset.realmsample W/System.err:     at com.amitshekhar.server.ClientServer.run(ClientServer.java:78)`

Why i cannot see any database?

**Comment by amitshekhariitbhu** [comment]
Realm is not supported.

**Comment by oksett** [comment]
What do you mean? I created simple project with one POJO class, nothing else.

**Comment by amitshekhariitbhu** [comment]
I will add the support for the Realm very soon.
