### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by VishalJogiya** [amitshekhariitbhu/Android-Debug-Database#73]
Often Times It happens With me and my friend. Tested on Different Devices.
Don't Know Y!!!!
while it works on Wifi LAN

![issue](https://user-images.githubusercontent.com/13519747/28970714-2c8c1254-7947-11e7-892b-2b542647e3cf.png)

**Comment by amitshekhariitbhu** [comment]
Let me know, how you are using it. Wifi or cable?

**Comment by VishalJogiya** [comment]
we are using Cable.(Not Working) sometimes works. some times dont.
Works better on wifi Lan

**Comment by amitshekhariitbhu** [comment]
It is made for Wifi. Let me come up with the better solution.
Try running this command on the terminal -  `adb forward tcp:8080 tcp:8080`

**Comment by VishalJogiya** [comment]
Ok Thanks I'll try this on Monday morning...

**Comment by jihin** [comment]
I have the same issue

**Comment by ParadiseHell** [comment]
I have the same issue using wifi
