### ISSUE TITLE
App crashes when I try to load provided URL 

### ISSUE THREAD

**Issue by garfieldcoked** [amitshekhariitbhu/Android-Debug-Database#8]
Hi,

Saw your post on Medium and thought I would try this out but I am not having much luck. When the app starts up I see the URL but when i try to open, the app crashes and the following error is displayed:

`
E/AndroidRuntime: FATAL EXCEPTION: Thread-49637
     Process: <app.id>, PID: 8713
          java.lang.NullPointerException: Attempt to get length of null array
          at com.amitshekhar.server.ClientServer.getDBList(ClientServer.java:412)
          at com.amitshekhar.server.ClientServer.handle(ClientServer.java:216)
          at com.amitshekhar.server.ClientServer.run(ClientServer.java:128)
          at java.lang.Thread.run(Thread.java:818)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
E/AbstractTracker: mTrackerAsyncQueryHandler is null
`

Do you know what the error issue might be. Not sure if its related but I am using DBFlow ORM.

**Comment by amitshekhariitbhu** [comment]
It works with android SQLite. Need to extend support for the DBFlow ORM.

**Comment by garfieldcoked** [comment]
OK Thank you.

**Comment by garfieldcoked** [comment]
It actually works with DBFLow. My database was not initialized when i tried to view. After initializing it works. Thank you for an awesome tool.
