### ISSUE TITLE
Keeps on loading in the browser

### ISSUE THREAD

**Issue by venkat20390** [amitshekhariitbhu/Android-Debug-Database#80]
I have added the Android Debug Database in my gradle file. The generated URL keeps on loading and doesn't show the content of the database.

**Comment by venkat20390** [comment]
I am using Splunk Mint bug tracking library (compile "com.splunk.mint:mint:4.4.0") to find the crashes in the released app builds. After disabling the library in Gradle, this library start working properly.

It will be great, if you could look into this issue and fix it.

**Comment by amitshekhariitbhu** [comment]
Great, I will check it.
