### ISSUE TITLE
Can you add a function to operate the file under the data directory?

### ISSUE THREAD

**Issue by liupeng110** [amitshekhariitbhu/Android-Debug-Database#82]
Can you add a function to operate the file under the data directory?

crud files in the data directory  
"data" means... 
/data/data/packageName/
/data/data/packageName/files/
and so on ..

**Comment by amitshekhariitbhu** [comment]
Yes, but you can also add this, like [here](https://github.com/amitshekhariitbhu/Android-Debug-Database#adding-custom-database-files) it is mentioned.

**Comment by liupeng110** [comment]
Like a web file manager

**Comment by amitshekhariitbhu** [comment]
Ok, this feature is in pipeline.

**Comment by liupeng110** [comment]
Thank you very much indeed,

**Comment by amitshekhariitbhu** [comment]
You can do now by adding custom database files.
