### ISSUE TITLE
Where are the HTML source or UI files?

### ISSUE THREAD

**Issue by john20xdoe** [amitshekhariitbhu/Android-Debug-Database#87]
I would like to help modify the web page shown in the browser (modify for responsiveness, etc) since it's difficult to traverse. However I can't find it in the repository, only .java files. Any one can point me to the right direction?

**Comment by amitshekhariitbhu** [comment]
It is present [here](https://github.com/amitshekhariitbhu/Android-Debug-Database/tree/master/debug-db/src/main/assets).

**Comment by john20xdoe** [comment]
THanks @amitshekhariitbhu
