### ISSUE TITLE
Genymotion problems

### ISSUE THREAD

**Issue by khaledkhj** [amitshekhariitbhu/Android-Debug-Database#88]
Hi,

Since updating Android Studio to 3, it stopped working!
It is giving http://10.0.3.15:8081 without configuring the bridge, and it is not working!

When configuring the bridge, the genymotion could not connect to network
and It is giving http://0.0.0.0:8081 since not connection to network!
I tried adb forward tcp:8080 tcp:8080, and still not working!

Any help please!

Thank you.

**Comment by didib2017** [comment]
Hi ! it work with Genymotion. Stop your device. Go to Genymotion setting and change the network bridge, select wireless connection.

**Comment by khaledkhj** [comment]
Thank you @didib2017, I did try same thing a few times but I was not able to even run the Genymotion!
But After restarting my PC and doing so, it worked!
