### ISSUE TITLE
Can't execute script with join

### ISSUE THREAD

**Issue by izayarniy** [amitshekhariitbhu/Android-Debug-Database#92]
I can't test script which contains joins.

`select * from outfit as out inner join garment2outfit as g2o on out.id = g2o.id`

This script works properly when I execute it in app through db.query("select *

**Comment by amitshekhariitbhu** [comment]
I tried this query in `SELECT questions.question_text FROM questions INNER JOIN options ON questions.id=options.question_id` in the [project](https://github.com/MindorksOpenSource/android-mvvm-architecture) and it's working.
