### ISSUE TITLE
Android 7 Lenovo tab 4 8

### ISSUE THREAD

**Issue by vospunt** [amitshekhariitbhu/Android-Debug-Database#97]
After access to http://ip:port/ in PC's webbrowser, application will crash and i cant browse db.
Problem has Lenovo tab 4 with Android 7.1.1.
When i want to try it again, i can not access the url ( it is always loading ).

Lenovo tab 3 8 with Android 6.0 works fine.

**Comment by amitshekhariitbhu** [comment]
Its weird. But let me check.

**Comment by vospunt** [comment]
i am sorry, probably false alarm, there was any problem with gradle, after fix my gradle file, your library is working.
